---
# INTERFEROMETER
# --------------
interferometer:

  - LinearPolariser:
      orientation: 0.

  - UniaxialCrystal:
      orientation: 45
      cut_angle: 0
      thickness: 3.5e-3
      material: 'a-BBO'

  - QuarterWaveplate:
      orientation: 90
