image: python:3.7-alpine

pages:
  script:
  #- pip install -U sphinx
  #- pip install sphinx_rtd_theme
  #- sphinx-build -d _build/doctrees docs/source docs/.build/html
  - mv docs/.build/html public
  artifacts:
        paths:
        - public
  only:
  - main
