---
# demo instrument configuration file for pycis.model, for the single_delay_pixelated instrument type

# CAMERA
# ------
# example is FLIR BlackFly S polarised camera
camera:
  sensor_format:
    - 2448  # x
    - 2048  # y
  pixel_size: 3.45e-6  # metres
  bit_depth: 12
  qe: 0.35
  epercount: 0.46
  cam_noise: 2.5  # e-
  type: 'monochrome_polarised'

# OPTICS
# ------
# Focal lengths (in metres) of lenses. Lens order is front-to-back.
lens_1_focal_length: 70.e-3
lens_2_focal_length: 105.e-3
lens_3_focal_length: 150.e-3


# INTERFEROMETER
# --------------
# - component order is front-to-back, first component listed is the first the light hits.
# - angles are in degrees.
# - thicknesses are in metres.
interferometer:

  - LinearPolariser:
      orientation: 0.

  - UniaxialCrystal:
      orientation: 45.
      cut_angle: 0.
      thickness: 6.5e-3
      material: 'a-BBO'

  - QuarterWaveplate:
      orientation: 90.