---
# demo instrument configuration file for pycis.model, for the single_delay_linear instrument type

# CAMERA
# ------
# FLIR BlackFly S
camera:
  bit_depth: 12
  sensor_format:
    - 2448  # x
    - 2048  # y
  pixel_size: 3.45e-6  # metres
  qe: 0.35
  epercount: 0.46
  cam_noise: 2.5  # e-
  type: 'monochrome'

# OPTICS
# ------
lens_1_focal_length: 70.e-3
lens_2_focal_length: 105.e-3
lens_3_focal_length: 150.e-3


# INTERFEROMETER
# --------------
interferometer:

  - LinearPolariser:
      orientation: 0

  - UniaxialCrystal:
      orientation: 45
      cut_angle: 45
      thickness: 8.e-3
      material: 'a-BBO'

  - LinearPolariser:
      orientation: 0