---
# demo instrument configuration file for pycis.model, for the single_delay_pixelated instrument type

# CAMERA
# ------
# example is FLIR BlackFly S polarised camera
camera:
  sensor_format:
    - 2450  # x
    - 2050  # y
  pixel_size: 3.45e-6  # metres
  bit_depth: 12
  qe: 0.35
  epercount: 0.46
  cam_noise: 2.5  # e-
  type: 'monochrome_polarised'

# OPTICS
# ------
# Focal lengths (in metres) of lenses. Lens order is front-to-back.
lens_1_focal_length: 20.e-3
lens_2_focal_length: 102.e-3
lens_3_focal_length: 50.e-3


# INTERFEROMETER
# --------------
# - component order is front-to-back, first component listed is the first the light hits.
# - angles are in degrees.
# - thicknesses are in metres.
interferometer:

  - LinearPolariser:
     orientation: 22.5

  - UniaxialCrystal:
     orientation: 0
     cut_angle: 45
     thickness: 8.e-3
     material: 'a-BBO'

  - UniaxialCrystal:
     orientation: 45
     cut_angle: 0
     thickness: 9.8e-3
     material: 'a-BBO'

  - QuarterWaveplate:
     orientation: 90
