---
# an example configuration file for pycis.model

# CAMERA
# ------


# OPTICS
# ------

# the camera / sensor parameters are inferred from phase.nc
# Focal length (in metres) of lenses. Lens order is front-to-back.
focal_length_lens_1: 70.e-3
focal_length_lens_2: 105.e-3
focal_length_lens_3: 150.e-3


# INTERFEROMETER
# --------------


# Interferometer
# - component order is front-to-back, first component listed is the first the light hits.
# - angles are in degrees and thicknesses are in metres.
# - crystal material must be
interferometer:

  polariser:
    orientation: 0.

  waveplate:
    orientation: 45.
    thickness: 6.5e-3
    thickness_std: 0.5e-3
    material: 'a-BBO'

  quarterwaveplate:
    orientation: 90.

interferometer_orientation: 0.