---
# INTERFEROMETER
# --------------
interferometer:

  - LinearPolariser:
      orientation: 22.5

  - UniaxialCrystal:
      orientation: 0
      cut_angle: 45
      thickness: 3.5e-3
      material: 'a-BBO'

  - UniaxialCrystal:
      orientation: 45
      cut_angle: 45
      thickness: 3.5e-3
      material: 'a-BBO'

  - LinearPolariser:
      orientation: 22.5

# CAMERA
# ------
# FLIR BlackFly S
camera:
  bit_depth: 12
  sensor_format:
    - 2448  # x
    - 2048  # y
  pixel_size: 3.45e-6  # metres
  qe: 0.35
  epercount: 0.46
  cam_noise: 2.5  # e-
  type: 'monochrome'